-- Push Notification analytics live beside, never inside, Meta Ads campaign data.
-- The two source channels only meet in the read-only daily consolidation view.

create table public.push_campaigns (
  id bigint generated by default as identity primary key,
  account_id text not null references public.dashboard_accounts(meta_account_id),
  utm_campaign text not null,
  display_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint push_campaigns_utm_not_blank check (btrim(utm_campaign) <> ''),
  constraint push_campaigns_account_utm_key unique (account_id, utm_campaign),
  constraint push_campaigns_id_account_key unique (id, account_id)
);

create table public.push_daily_results (
  id bigint generated by default as identity primary key,
  account_id text not null references public.dashboard_accounts(meta_account_id),
  campaign_id bigint not null,
  reporting_date date not null,
  report_id text not null,
  generated_at timestamptz,
  report_timezone text not null,
  currency text not null,
  is_partial boolean not null,
  impressions bigint not null default 0,
  unfilled_impressions bigint not null default 0,
  viewable_impressions bigint not null default 0,
  clicks bigint not null default 0,
  source_ctr numeric(14,8) not null default 0,
  gross_revenue numeric(18,2) not null default 0,
  source_ecpm numeric(18,6) not null default 0,
  source_key text not null,
  source_sha256 text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint push_daily_campaign_account_fk
    foreign key (campaign_id, account_id)
    references public.push_campaigns(id, account_id),
  constraint push_daily_account_date_campaign_key
    unique (account_id, reporting_date, campaign_id),
  constraint push_daily_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint push_daily_nonnegative_check check (
    impressions >= 0 and unfilled_impressions >= 0 and
    viewable_impressions >= 0 and clicks >= 0 and
    source_ctr >= 0 and gross_revenue >= 0 and source_ecpm >= 0
  )
);

create index push_daily_account_date_idx
  on public.push_daily_results (account_id, reporting_date desc);
create index push_daily_campaign_date_idx
  on public.push_daily_results (campaign_id, reporting_date desc);

create schema if not exists private;
create table private.push_import_batches (
  id bigint generated by default as identity primary key,
  batch_key text not null unique,
  account_id text not null references public.dashboard_accounts(meta_account_id),
  reporting_date date not null,
  report_id text not null,
  generated_at timestamptz,
  is_partial boolean not null,
  currency text not null,
  report_timezone text not null,
  source_name text not null,
  source_sha256 text not null,
  status text not null,
  totals jsonb not null,
  audit jsonb not null,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.push_campaigns enable row level security;
alter table public.push_daily_results enable row level security;

create policy public_read_push_campaigns
on public.push_campaigns for select
to anon, authenticated
using (true);

create policy public_read_push_daily_results
on public.push_daily_results for select
to anon, authenticated
using (true);

revoke all on public.push_campaigns from anon, authenticated;
revoke all on public.push_daily_results from anon, authenticated;
grant select on public.push_campaigns to anon, authenticated;
grant select on public.push_daily_results to anon, authenticated;

create or replace view public.v_push_daily
with (security_invoker = true)
as
select
  r.id,
  r.account_id,
  r.campaign_id,
  c.utm_campaign,
  c.display_name as label,
  r.reporting_date as date,
  r.report_id,
  r.generated_at,
  r.report_timezone,
  r.currency,
  r.is_partial,
  r.impressions,
  r.unfilled_impressions,
  r.viewable_impressions,
  r.clicks,
  r.source_ctr,
  r.gross_revenue,
  r.source_ecpm,
  case when r.impressions > 0 then r.clicks::numeric / r.impressions else null end as calculated_ctr,
  case when r.impressions > 0 then r.gross_revenue / r.impressions * 1000 else null end as calculated_ecpm
from public.push_daily_results r
join public.push_campaigns c
  on c.id = r.campaign_id and c.account_id = r.account_id;

create or replace view public.v_combined_daily
with (security_invoker = true)
as
with meta as (
  select
    account_id,
    date,
    max(badge) as meta_badge,
    count(distinct campaign_id) as meta_campaigns,
    sum(spend) as meta_spend,
    sum(cost) as meta_cost,
    sum(rev) as meta_gross_revenue,
    sum(rev_adj) as meta_net_revenue,
    sum(profit) as meta_profit
  from public.v_daily
  where typ = 'msgs'
  group by account_id, date
),
push as (
  select
    account_id,
    date,
    bool_or(is_partial) as push_is_partial,
    count(distinct campaign_id) as push_campaigns,
    sum(impressions) as push_impressions,
    sum(clicks) as push_clicks,
    sum(gross_revenue) as push_gross_revenue
  from public.v_push_daily
  group by account_id, date
)
select
  coalesce(m.account_id, p.account_id) as account_id,
  coalesce(m.date, p.date) as date,
  coalesce(m.meta_campaigns, 0) as meta_campaigns,
  coalesce(m.meta_spend, 0) as meta_spend,
  coalesce(m.meta_cost, 0) as meta_cost,
  coalesce(m.meta_gross_revenue, 0) as meta_gross_revenue,
  coalesce(m.meta_net_revenue, 0) as meta_net_revenue,
  coalesce(m.meta_profit, 0) as meta_profit,
  coalesce(p.push_campaigns, 0) as push_campaigns,
  coalesce(p.push_impressions, 0) as push_impressions,
  coalesce(p.push_clicks, 0) as push_clicks,
  coalesce(p.push_gross_revenue, 0) as push_gross_revenue,
  coalesce(m.meta_gross_revenue, 0) + coalesce(p.push_gross_revenue, 0) as total_gross_revenue,
  case
    when coalesce(m.meta_badge = 'parcial', false) or coalesce(p.push_is_partial, false)
      then 'parcial'
    else 'fechado'
  end as status
from meta m
full join push p
  on p.account_id = m.account_id and p.date = m.date;

grant select on public.v_push_daily to anon, authenticated;
grant select on public.v_combined_daily to anon, authenticated;

do $account_guard$
begin
  if not exists (
    select 1 from public.dashboard_accounts
    where meta_account_id = '2948780535467215'
      and currency = 'USD'
      and tax_rate = 0
  ) then
    raise exception 'DIZZ 1 USD is missing or has unexpected financial rules';
  end if;
end
$account_guard$;

insert into public.push_campaigns (account_id, utm_campaign, display_name)
values
  ('2948780535467215', 'PHES-1', 'PHES-1'),
  ('2948780535467215', 'PHES-2', 'PHES-2'),
  ('2948780535467215', 'PHES-3', 'PHES-3'),
  ('2948780535467215', 'PHES-4', 'PHES-4'),
  ('2948780535467215', 'PHES-5', 'PHES-5'),
  ('2948780535467215', 'PHES-6-CAMP-CARTAODECREDITO', 'PHES-6-CAMP-CARTAODECREDITO')
on conflict (account_id, utm_campaign) do update
set display_name = excluded.display_name,
    updated_at = now();

with source_rows (
  reporting_date, report_id, generated_at, is_partial, utm_campaign,
  impressions, unfilled_impressions, viewable_impressions, clicks,
  source_ctr, gross_revenue, source_ecpm, source_key, source_sha256
) as (
  values
    ('2026-09-16'::date, '10841400468', '2026-09-17 10:08:08-03'::timestamptz, false, 'PHES-1', 488, 0, 461, 164, 0.3361, 27.78, 56.93, 'utm_campaign=PHES-1', 'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae'),
    ('2026-09-16'::date, '10841400468', '2026-09-17 10:08:08-03'::timestamptz, false, 'PHES-2', 342, 0, 315, 114, 0.3333, 12.22, 35.74, 'utm_campaign=PHES-2', 'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae'),
    ('2026-09-16'::date, '10841400468', '2026-09-17 10:08:08-03'::timestamptz, false, 'PHES-4', 193, 0, 228, 49, 0.2539, 8.26, 42.79, 'utm_campaign=PHES-4', 'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae'),
    ('2026-09-16'::date, '10841400468', '2026-09-17 10:08:08-03'::timestamptz, false, 'PHES-5', 219, 0, 224, 77, 0.3516, 7.78, 35.53, 'utm_campaign=PHES-5', 'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae'),
    ('2026-09-16'::date, '10841400468', '2026-09-17 10:08:08-03'::timestamptz, false, 'PHES-3', 171, 0, 158, 55, 0.3216, 7.62, 44.55, 'utm_campaign=PHES-3', 'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae'),
    ('2026-09-16'::date, '10841400468', '2026-09-17 10:08:08-03'::timestamptz, false, 'PHES-6-CAMP-CARTAODECREDITO', 139, 0, 159, 7, 0.0504, 2.62, 18.85, 'utm_campaign=PHES-6-CAMP-CARTAODECREDITO', 'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae'),
    ('2026-09-17'::date, '10841411186', '2026-09-17 10:09:34-03'::timestamptz, true, 'PHES-5', 45, 0, 39, 14, 0.3111, 4.37, 97.12, 'utm_campaign=PHES-5', '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7'),
    ('2026-09-17'::date, '10841411186', '2026-09-17 10:09:34-03'::timestamptz, true, 'PHES-6-CAMP-CARTAODECREDITO', 72, 0, 62, 6, 0.0833, 2.30, 31.94, 'utm_campaign=PHES-6-CAMP-CARTAODECREDITO', '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7'),
    ('2026-09-17'::date, '10841411186', '2026-09-17 10:09:34-03'::timestamptz, true, 'PHES-2', 15, 0, 15, 5, 0.3333, 1.13, 75.23, 'utm_campaign=PHES-2', '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7'),
    ('2026-09-17'::date, '10841411186', '2026-09-17 10:09:34-03'::timestamptz, true, 'PHES-4', 5, 0, 5, 1, 0.2, 0.90, 179.86, 'utm_campaign=PHES-4', '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7'),
    ('2026-09-17'::date, '10841411186', '2026-09-17 10:09:34-03'::timestamptz, true, 'PHES-1', 8, 0, 7, 3, 0.375, 0.36, 45.46, 'utm_campaign=PHES-1', '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7'),
    ('2026-09-17'::date, '10841411186', '2026-09-17 10:09:34-03'::timestamptz, true, 'PHES-3', 3, 0, 2, 1, 0.3333, 0.04, 14.77, 'utm_campaign=PHES-3', '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7')
)
insert into public.push_daily_results (
  account_id, campaign_id, reporting_date, report_id, generated_at,
  report_timezone, currency, is_partial, impressions, unfilled_impressions,
  viewable_impressions, clicks, source_ctr, gross_revenue, source_ecpm,
  source_key, source_sha256
)
select
  '2948780535467215', c.id, s.reporting_date, s.report_id, s.generated_at,
  'America/Sao_Paulo', 'USD', s.is_partial, s.impressions,
  s.unfilled_impressions, s.viewable_impressions, s.clicks, s.source_ctr,
  s.gross_revenue, s.source_ecpm, s.source_key, s.source_sha256
from source_rows s
join public.push_campaigns c
  on c.account_id = '2948780535467215'
 and c.utm_campaign = s.utm_campaign
on conflict (account_id, reporting_date, campaign_id) do update
set report_id = excluded.report_id,
    generated_at = excluded.generated_at,
    report_timezone = excluded.report_timezone,
    currency = excluded.currency,
    is_partial = excluded.is_partial,
    impressions = excluded.impressions,
    unfilled_impressions = excluded.unfilled_impressions,
    viewable_impressions = excluded.viewable_impressions,
    clicks = excluded.clicks,
    source_ctr = excluded.source_ctr,
    gross_revenue = excluded.gross_revenue,
    source_ecpm = excluded.source_ecpm,
    source_key = excluded.source_key,
    source_sha256 = excluded.source_sha256,
    updated_at = now();

insert into private.push_import_batches (
  batch_key, account_id, reporting_date, report_id, generated_at, is_partial,
  currency, report_timezone, source_name, source_sha256, status, totals, audit,
  completed_at
)
values
  (
    'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae',
    '2948780535467215', '2026-09-16', '10841400468',
    '2026-09-17 10:08:08-03', false, 'USD', 'America/Sao_Paulo',
    'SHEIN AUST - BROADCAST (set. 16, 2026) (5).csv',
    'c9dfa4ca2ae71836c9d5ac7dc82581ef28cbd045d2285010727a70150aac48ae',
    'applied',
    '{"rows":6,"impressions":1552,"clicks":466,"gross_revenue":66.28}'::jsonb,
    '{"viewable_exceeds_total":["PHES-4","PHES-5","PHES-6-CAMP-CARTAODECREDITO"]}'::jsonb,
    now()
  ),
  (
    '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7',
    '2948780535467215', '2026-09-17', '10841411186',
    '2026-09-17 10:09:34-03', true, 'USD', 'America/Sao_Paulo',
    'SHEIN AUST - BROADCAST (set. 17, 2026) (1).csv',
    '85efd40e49249539ffe0826890be9e418387271801f54e9bf158b69c68c941e7',
    'applied',
    '{"rows":6,"impressions":148,"clicks":30,"gross_revenue":9.10}'::jsonb,
    '{"viewable_exceeds_total":[]}'::jsonb,
    now()
  )
on conflict (batch_key) do nothing;

do $push_audit$
declare
  day_16 numeric;
  day_17 numeric;
begin
  select sum(gross_revenue) into day_16
  from public.v_push_daily
  where account_id = '2948780535467215' and date = '2026-09-16';

  select sum(gross_revenue) into day_17
  from public.v_push_daily
  where account_id = '2948780535467215' and date = '2026-09-17';

  if day_16 is distinct from 66.28 or day_17 is distinct from 9.10 then
    raise exception 'Push revenue reconciliation failed: %, %', day_16, day_17;
  end if;
end
$push_audit$;
